image: node:14.15.1

stages: 
  - build
  - deploy

build:
  stage: build
  variables:
    PUBLIC_URL: https://conghuynhho.gitlab.io/shopping-cart/
  script: 
    - yarn install
    - yarn build
  artifacts: 
    paths:
      - build/

pages: 
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - mv build public
  artifacts:
    paths:
      - public