export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const REMOVE_A_PRODUCT = 'REMOVE_A_PRODUCT';
export const PENDING_REMOVE_PRODUCT = 'PENDING_REMOVE_PRODUCT'; 
export const PENDING_ADD_PRODUCT = 'PENDING_ADD_PRODUCT';
export const UPDATE_CART = 'UPDATE_CART';
